# Generated by Django 5.2.13 on 2026-04-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploadthing_key',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='created_at',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='weddings/'),
            preserve_default=False,
        ),
    ]
